/**
 * Raw payload shape returned by the V1 minute-data endpoint.
 * This is a temporary bridge type — it mirrors the legacy EddiData contract
 * and should be replaced once a proper provider adapter platform exists.
 *
 * Energy fields are in Joules. Date/time parts are currently emitted by the
 * legacy endpoint in UTC and must be converted to the installation timezone
 * before they are used for UI freshness or chart labelling.
 *
 * Field reference:
 *   gep  - Generated Positive: energy generated by solar panels
 *   h1d  - Heater-1 Diverted: energy diverted from panels to immersion
 *   h1b  - Heater-1 Boost: energy sent to immersion via boost (may come from grid)
 *   imp  - Imported: energy imported from the grid
 *   exp  - Exported: energy exported to the grid
 *   v1   - Supply Voltage (centi-volts)
 *   frq  - Supply Frequency (centi-Hertz)
 */
export interface V1MinuteRecord {
  yr: number;
  mon: number;
  dom: number;
  dow: 'Sun' | 'Mon' | 'Tues' | 'Wed' | 'Thurs' | 'Fri' | 'Sat';
  hr?: number;
  min?: number;
  imp?: number;
  gep?: number;
  exp?: number;
  h1d?: number;
  h1b?: number;
  pect1?: number;
  pect2?: number;
  v1?: number;
  frq?: number;
}
